### ISSUE TITLE
Merge Sort Algorithm in Java

### ISSUE THREAD

**Issue by abhaysinghr516** [abhaysinghr516/Algorithms#19]

**Comment by Rajat119** [comment]
Pls assign me this issue I'll complete it today only

**Comment by Yash-Ainapure** [comment]
heyy ,I would like to contribute here . @Rajat119  are you working on it? otherwise assign me this issue .

**Comment by abhaysinghr516** [comment]
@Yash-Ainapure you can work on this

**Comment by Yash-Ainapure** [comment]
ok

**Comment by Rajat119** [comment]
@abhaysinghr516  I had already completed that and you had merged that too earlier how come is this open again

**Comment by abhaysinghr516** [comment]
Sorry, @Rajat119, I thought you weren't working on it and assumed you had already made 4-5 PRs, so I decided to give it to Yash for Hacktober. Apologies for any confusion.
