### ISSUE TITLE
Quicksort Algorithm in Java

### ISSUE THREAD

**Issue by abhaysinghr516** [abhaysinghr516/Algorithms#25]

**Comment by Rajat119** [comment]
Pls assign me this issue I'll complete it today only

**Comment by abhaysinghr516** [comment]
@Rajat119  Assigned to you

**Comment by Rajat119** [comment]
@abhaysinghr516  done with the issue pls review it

**Comment by abhaysinghr516** [comment]
Create pull request

**Comment by Rajat119** [comment]
sorry forgot to add the label pls don't accept it creating fresh one
