### ISSUE TITLE
Bubble Sort Algorithm in Python

### ISSUE THREAD

**Issue by abhaysinghr516** [abhaysinghr516/Algorithms#70]

**Comment by yashwantpradhan** [comment]
Please assign me this issue. I can write the most optimized code. Thank you.

**Comment by AshaHolla** [comment]
pls assign to me

**Comment by abhaysinghr516** [comment]
@AshaHolla this is already assigned to @yashwantpradhan. You can create new issues

**Comment by abhaysinghr516** [comment]
#83
