### ISSUE TITLE
Kruskal's Algorithm in C

### ISSUE THREAD

**Issue by abhaysinghr516** [abhaysinghr516/Algorithms#72]

**Comment by yashwantpradhan** [comment]
Please assign me this issue. I want to make some significant contributions in this repository. Note:- I am not spamming.

**Comment by abhaysinghr516** [comment]
Sure, I'll assign the issue.

**Comment by yashwantpradhan** [comment]
I have made a pull request for this. Please review it and merge my pull request. Thank You.

**Comment by abhaysinghr516** [comment]
It seems that the pull request hasn't been created;

**Comment by yashwantpradhan** [comment]
I am sorry for my previous comment. It was my mistake. Now I have made the pull request.

**Comment by abhaysinghr516** [comment]
No worries!
