### ISSUE TITLE
Kruskal's Algorithm in Python

### ISSUE THREAD

**Issue by abhaysinghr516** [abhaysinghr516/Algorithms#75]

**Comment by samikshakale** [comment]
I'm looking to get started contributing to open-source and would love to be assigned to this issue. I have a lot of practice with common tree/graph algorithms and implementing them so I'm hoping that I can get this done quickly.

**Comment by samikshakale** [comment]
Thanks! I just created a pr

**Comment by abhaysinghr516** [comment]
#93
