### ISSUE TITLE
Kruskal's Algorithm in Go

### ISSUE THREAD

**Issue by abhaysinghr516** [abhaysinghr516/Algorithms#76]

**Comment by yashwantpradhan** [comment]
Please assign me this issue. I can write the code.

**Comment by yashwantpradhan** [comment]
package main

import (
	"fmt"
	"sort"
)

// Edge represents an edge in the graph.
type Edge struct {
	src, dest, weight int
}

// ByWeight is a custom type to sort edges by weight.
type ByWeight []Edge

func (e ByWeight) Len() int           { return len(e) }
func (e ByWeight) Swap(i, j int)      { e[i], e[j] = e[j], e[i] }
func (e ByWeight) Less(i, j int) bool { return e[i].weight < e[j].weight }

// Graph represents a graph with a list of edges.
type Graph struct {
	edges []Edge
}

// AddEdge adds an edge to the graph.
func (g *Graph) AddEdge(src, dest, weight int) {
	g.edges = append(g.edges, Edge{src, dest, weight})
}

// Find returns the parent of a set in the forest.
func Find(parent []int, i int) int {
	if parent[i] != i {
		parent[i] = Find(parent, parent[i])
	}
	return parent[i]
}

// Union performs a union operation on two sets.
func Union(parent []int, rank []int, x, y int) {
	rootX := Find(parent, x)
	rootY := Find(parent, y)

	if rank[rootX] < rank[rootY] {
		parent[rootX] = rootY
	} else if rank[rootX] > rank[rootY] {
		parent[rootY] = rootX
	} else {
		parent[rootY] = rootX
		rank[rootX]++
	}
}

// Kruskal finds the minimum spanning tree of the graph.
func (g *Graph) Kruskal() []Edge {
	// Sort edges by weight in non-decreasing order.
	sort.Sort(ByWeight(g.edges))

	// Initialize parent and rank arrays for union-find.
	parent := make([]int, len(g.edges))
	rank := make([]int, len(g.edges))
	minimumSpanningTree := []Edge{}

	for i := range parent {
		parent[i] = i
		rank[i] = 0
	}

	// Process each edge in sorted order.
	for _, edge := range g.edges {
		rootSrc := Find(parent, edge.src)
		rootDest := Find(parent, edge.dest)

		// If adding this edge doesn't form a cycle, include it in the minimum spanning tree.
		if rootSrc != rootDest {
			minimumSpanningTree = append(minimumSpanningTree, edge)
			Union(parent, rank, rootSrc, rootDest)
		}
	}

	return minimumSpanningTree
}

func main() {
	graph := Graph{}

	// Example edges
	graph.AddEdge(0, 1, 2)
	graph.AddEdge(0, 2, 4)
	graph.AddEdge(1, 2, 1)
	graph.AddEdge(1, 3, 7)
	graph.AddEdge(2, 4, 3)
	graph.AddEdge(3, 4, 5)

	minimumSpanningTree := graph.Kruskal()

	fmt.Println("Edges in the minimum spanning tree:")
	for _, edge := range minimumSpanningTree {
		fmt.Printf("(%d, %d) -> %d\n", edge.src, edge.dest, edge.weight)
	}
}

**Comment by yashwantpradhan** [comment]
I have a question. Can you please tell me that even after you have merged my pull request, my hactoberfest profile says 0/4 in the progess bar??
